--- 
name: MijnAhoy
extensions: 
- extension-name-here
- second-extension-name
bbver: 4.6
sdk: /Library/Ruby/Gems/1.8/gems/rhodes-2.0.0
build: debug
applog: rholog.txt
version: 1.0
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
sdkversion: 2.0.0
vendor: rhomobile
iphone: 
  provisionprofile: 
  sdk: iphonesimulator3.0
  codesignidentity: 
  entitlements: 
  configuration: Debug
